#!/usr/bin/env bash
# Build (or rebuild) the macOS .app launcher for Kayenta Explorer.
#
# The launcher is a tiny LSUIElement bundle that:
#   1. Resolves the project directory (recorded at build time below).
#   2. Runs start.sh detached so the .app can return immediately.
#   3. Polls for Vite's "Local: http://localhost:NNNN" banner and opens
#      the dashboard in the default browser when it appears.
#   4. Posts macOS notifications at each transition for visible feedback
#      — important because LSUIElement bundles have no Dock tile.
#
# Idempotent: rerun any time to refresh the launcher after the repo
# moves or after the favicon changes.
#
# Usage:
#   ./build-launcher.sh                  # installs to ~/Desktop/Kayenta Explorer.app
#   ./build-launcher.sh /Applications    # installs into the given parent dir
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST_PARENT="${1:-$HOME/Desktop}"
APP_PATH="$DEST_PARENT/Kayenta Explorer.app"

if [ ! -f "$REPO_DIR/start.sh" ]; then
  echo "✗ build-launcher must be run from inside the kayenta-explorer repo (no start.sh next to it)" >&2
  exit 1
fi

echo "Repo:     $REPO_DIR"
echo "Bundle:   $APP_PATH"
echo

# ── 1. Clean + scaffold ──────────────────────────────────────────────────
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS" "$APP_PATH/Contents/Resources"

# ── 2. Info.plist ────────────────────────────────────────────────────────
cat > "$APP_PATH/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Kayenta Explorer</string>
    <key>CFBundleDisplayName</key>
    <string>Kayenta Explorer</string>
    <key>CFBundleIdentifier</key>
    <string>com.local.kayenta-explorer.launcher</string>
    <key>CFBundleVersion</key>
    <string>1.1</string>
    <key>CFBundleShortVersionString</key>
    <string>1.1</string>
    <key>CFBundleExecutable</key>
    <string>KayentaExplorer</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# ── 3. Launcher script — REPO_DIR is baked in at build time ──────────────
# Escape any double-quotes / backslashes for safe embedding inside the
# heredoc's "$REPO_DIR" literal.
ESC_REPO_DIR="${REPO_DIR//\\/\\\\}"
ESC_REPO_DIR="${ESC_REPO_DIR//\"/\\\"}"

cat > "$APP_PATH/Contents/MacOS/KayentaExplorer" <<LAUNCHER
#!/usr/bin/env bash
# Kayenta Explorer launcher — auto-generated by build-launcher.sh.
# DO NOT edit in place; rerun ./build-launcher.sh from the repo instead.
set -u

PROJECT_DIR="$ESC_REPO_DIR"
LOG_FILE="\$PROJECT_DIR/.launcher.log"

# Finder launches GUI apps with a minimal PATH — Homebrew node won't be
# found by default. Inject the common Homebrew bin paths up front.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\${PATH:-}"

notify() {
  /usr/bin/osascript -e "display notification \"\$1\" with title \"Kayenta Explorer\"" >/dev/null 2>&1 || true
}

resolve_web_port() {
  # Vite logs the active port in .vite.log; fall back to the default 3000.
  if [ -s "\$PROJECT_DIR/.vite.log" ]; then
    local p
    p=\$(grep -oE 'Local:[[:space:]]+http://localhost:[0-9]+' "\$PROJECT_DIR/.vite.log" 2>/dev/null | tail -1 | grep -oE '[0-9]+\$')
    if [ -n "\$p" ]; then echo "\$p"; return; fi
  fi
  echo "3000"
}

# LSUIElement bundles sometimes fail \`open URL\` because LaunchServices
# doesn't wire the URL handler from a non-UI parent. AppleScript's
# "open location" goes through the same path Cmd-click uses, which is
# reliable from any GUI context. Try both — whichever wins, wins.
open_dashboard() {
  local url="\$1"
  /usr/bin/osascript -e "open location \"\$url\"" >/dev/null 2>&1 \\
    || /usr/bin/open "\$url" \\
    || /usr/bin/open -a "Safari" "\$url" 2>/dev/null \\
    || true
}

{
  echo "=== launcher \$(date) ==="
  if [ ! -d "\$PROJECT_DIR" ]; then
    notify "Project dir missing: \$PROJECT_DIR — rerun build-launcher.sh"
    exit 1
  fi
  cd "\$PROJECT_DIR" || { notify "cd failed: \$PROJECT_DIR"; exit 1; }

  # "Already running" detection — be strict so we don't open the browser
  # against a stranger that happens to be on our port. All three must agree:
  #   1. server/.api.pid points to a live process
  #   2. server/.port exists and someone is LISTENing on that port
  #   3. that listener's pid matches .api.pid (so it's actually our API)
  if [ -s server/.port ] && [ -s server/.api.pid ]; then
    PORT=\$(cat server/.port)
    OUR_PID=\$(cat server/.api.pid)
    LIVE_LISTENER=\$(lsof -ti:"\$PORT" -sTCP:LISTEN 2>/dev/null | head -1)
    if kill -0 "\$OUR_PID" 2>/dev/null && [ -n "\$LIVE_LISTENER" ] && [ "\$LIVE_LISTENER" = "\$OUR_PID" ]; then
      notify "Already running — opening dashboard."
      open_dashboard "http://localhost:\$(resolve_web_port)/"
      exit 0
    fi
  fi

  notify "Starting Kayenta Explorer…"
  nohup bash ./start.sh >> "\$LOG_FILE" 2>&1 &
  disown || true

  # Poll for vite's banner; open the browser when it appears.
  for _ in \$(seq 1 60); do
    if grep -qE 'Local:[[:space:]]+http://localhost:[0-9]+' "\$PROJECT_DIR/.vite.log" 2>/dev/null; then
      open_dashboard "http://localhost:\$(resolve_web_port)/"
      notify "Kayenta Explorer is running."
      exit 0
    fi
    sleep 0.5
  done

  notify "Startup taking longer than expected — check .launcher.log"
  open_dashboard "http://localhost:\$(resolve_web_port)/"
} >> "\$LOG_FILE" 2>&1
LAUNCHER

chmod +x "$APP_PATH/Contents/MacOS/KayentaExplorer"

# ── 4. App icon ──────────────────────────────────────────────────────────
# Derive AppIcon.icns from client/public/favicon.svg so the bundle stays
# in sync with the in-app theme. SVG → 1024 PNG via qlmanage, then
# downscale and assemble with iconutil.
ICONSET="$(mktemp -d)/AppIcon.iconset"
mkdir -p "$ICONSET"
SVG="$REPO_DIR/client/public/favicon.svg"

if [ -f "$SVG" ] && command -v qlmanage >/dev/null 2>&1 && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
  echo "Rendering favicon.svg → AppIcon.icns…"
  TMPDIR_RENDER="$(mktemp -d)"
  # qlmanage renders the Quick Look preview; for SVG that's a clean raster.
  qlmanage -t -s 1024 -o "$TMPDIR_RENDER" "$SVG" >/dev/null 2>&1
  BASE_PNG="$TMPDIR_RENDER/$(basename "$SVG").png"
  if [ -f "$BASE_PNG" ]; then
    for s in 16 32 64 128 256 512 1024; do
      sips -z "$s" "$s" "$BASE_PNG" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    done
    # @2x slots reuse the next size up — Apple's expected iconset layout
    cp "$ICONSET/icon_32x32.png"     "$ICONSET/icon_16x16@2x.png"
    cp "$ICONSET/icon_64x64.png"     "$ICONSET/icon_32x32@2x.png"
    cp "$ICONSET/icon_256x256.png"   "$ICONSET/icon_128x128@2x.png"
    cp "$ICONSET/icon_512x512.png"   "$ICONSET/icon_256x256@2x.png"
    cp "$ICONSET/icon_1024x1024.png" "$ICONSET/icon_512x512@2x.png"
    # 64 and 1024 are intermediates, not part of the canonical iconset
    rm -f "$ICONSET/icon_64x64.png" "$ICONSET/icon_1024x1024.png"
    iconutil -c icns "$ICONSET" -o "$APP_PATH/Contents/Resources/AppIcon.icns"
  else
    echo "  (qlmanage did not produce a PNG — bundle will use the default icon)"
  fi
  rm -rf "$TMPDIR_RENDER"
else
  echo "  (skipping icon generation — missing one of: favicon.svg, qlmanage, sips, iconutil)"
fi
rm -rf "$(dirname "$ICONSET")"

# ── 5. Ad-hoc sign so Gatekeeper allows it to launch ─────────────────────
# Unsigned .app bundles get blocked on first run with "cannot be opened"
# on modern macOS. An ad-hoc signature (identity '-') is enough for a
# locally-built launcher.
if command -v codesign >/dev/null 2>&1; then
  # Strip resource forks / Finder xattrs that qlmanage + tempdir IO leave
  # behind; codesign refuses to operate when those are present.
  xattr -cr "$APP_PATH" 2>/dev/null || true
  codesign --force --deep --sign - "$APP_PATH" >/dev/null 2>&1 || true
fi

# Bust Finder/LaunchServices icon cache so the new icon shows up right away.
touch "$APP_PATH"

echo
echo "✓ Built $APP_PATH"
echo "  Double-click it on the Desktop to launch Kayenta Explorer."
